codecov:
  notify:
    require_ci_to_pass: yes
  bot: medtunebot

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: no
