meta:
  name: medtune beta platform
  description: beta test
  version: iron-0.0.3

server:
  mode: LAS 
  port: 8005
  ssltls: false

database:
  type: postgres
  prod: medtune
  test: medtune-test
  creds:
    host: localhost
    port: 5432
    user: amine
    password: a
  
session:
  type: cookie
  random: true
  name: default-session
  secret: A0123456789

crypto:
  algo: id
  salt: TOOMUCHSALT:)

public:
  static: ./static

capsules:
  engine: docker
  setup:
    - image: medtune/inception-0.0.0
    - port:
      map: 10001:8500
    - volume:
      no-mapping: true
    - flags: -itd
