version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/medtune/beta-platform

    steps:
      - checkout
      
      - run:
          name: Compile package
          command: |
            go get ./...
            go build -o bin.out cmd/beta-platform
            ls -sh