version: '3'
services:
  #Database
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mdtn
      - POSTGRES_PASSWORD=mdtn
      - POSTGRES_DB=medtune

  platform-server:
    image: medtune/platform:beta.alpine-v0.1.0
    ports:
      - 8005:8005
    depends_on:
      - "postgres"
    links:
      - postgres:postgres
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2.00'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M