apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: test-app:v1
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: test-svc
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer