apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f deployments/docker-compose.k8s-gen.yml -o deployments/k8s-generated
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: chexray-pp
  name: chexray-pp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chexray-pp
    spec:
      containers:
      - image: medtune/capsul:chexray-pp-helper
        name: chexray-pp
        ports:
        - containerPort: 12030
        resources: {}
        volumeMounts:
        - mountPath: /medtune/data
          name: chexray-images
      restartPolicy: Always
      volumes:
      - name: chexray-images
        persistentVolumeClaim:
          claimName: chexray-images
status: {}
