apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f deployments/docker-compose.k8s-gen.yml -o deployments/k8s-generated
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mura-mn-v2-cam
  name: mura-mn-v2-cam
spec:
  ports:
  - name: "11020"
    port: 11020
    targetPort: 11020
  selector:
    io.kompose.service: mura-mn-v2-cam
status:
  loadBalancer: {}
