apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.replicas.yml -o deploy/kubernetes
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: chexray-dn-121
  name: chexray-dn-121
spec:
  ports:
  - name: "10031"
    port: 10031
    targetPort: 10031
  selector:
    io.kompose.service: chexray-dn-121
status:
  loadBalancer: {}
