apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.replicas.yml -o deploy/kubernetes
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: inception
  name: inception
spec:
  ports:
  - name: "10010"
    port: 10010
    targetPort: 10010
  selector:
    io.kompose.service: inception
status:
  loadBalancer: {}
