apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.k8s.yml -o deploy/kubernetes
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mnist
  name: mnist
spec:
  ports:
  - name: "10000"
    port: 10000
    targetPort: 10000
  selector:
    io.kompose.service: mnist
status:
  loadBalancer: {}
